site_name: Značka a rok výroby
site_description: Výrobní manuál pro modely
site_author: Hartje Production
docs_dir: docs

theme:
  name: material
  language: cs
  palette:
    primary: '#0b4ea2'
    accent: '#009fe3'
  custom_dir: overrides

extra_css:
  - styles/extra.css

plugins:
  - search
  - include-markdown:
      preserve_includer_indent: false
  - macros

extra:
  base_url: ''

markdown_extensions:
  - md_in_html
  - tables
  - admonition

nav:
  - Obecné:
      - Specifikace: obecne/specifikace.md
      - Bezpečnost: obecne/bezpecnost.md
      - Nástroje: obecne/nastroje.md
  - Modely:
      - Šablona:
          - Přehled: modely/Sablona/Přehled.md
          - Montáž: modely/Sablona/Montáž.md
          - Kusovníky: modely/Sablona/Kusovníky.md
  - Přílohy:
      - Tabulka momentů: prilohy/tabulka-momentu.md
